### PR TITLE
Feature/full ecbuild

### PR DESCRIPTION
**Pull request by svahl991**
Create a version of the MPAS-Model used by the JEDI project that can be built using CMake and used as an upstream project by the mpas-jedi project.

### CODE REVIEW

**Comment by jjguerrette** [comment]
Should the target of the PR be `develop-for-jedi`?  `master` is not updated presently in my fork, but in general is used to monitor the MPAS-Dev branch of the same name.

**Comment by svahl991** [comment]
@jjguerrette 
The MPAS-Model code that gets cloned and built is specified in the top-level CMakeLists.txt of the mpas-bundle repo. (If you look at my draft PR in that repo, you'll see right now it is cloning from my personal github branch.) When all this gets merged in, we'll change that to use the develop-for-jedi branch from your repo.

I don't think we want to change the actual name of the target that gets built to something specific to develop-for-jedi, if that's what you're suggesting. If we did, then we'd have to change the CMake code whenever we changed the git location of the source.

**Comment by svahl991** [comment]
@jjguerrette 
Oh wait, I just understood what you were saying. Yes, the actual PR will get merged to develop-for-jedi when we're ready to merge. I just created this draft PR quickly yesterday when I was getting things ready to show Mark O. But now I realize I don't actually need this draft PR right now.

**Comment by jjguerrette** [comment]
Yes Steve, I meant the target of the PR merge.  Sorry for the lack of clarity.  FYI, we can have a video call any time it might help discussions.

**Comment by svahl991** [comment]
@jjguerrette Yes, I just got confused by the term 'target' for a minute. My brain is in CMake space where that word has a different meaning. Thanks.

**Comment by svahl991** [comment]
This PR is no longer needed as the work has been accomplished through other PR's.

**Pull request closed without merging**
