### PR TITLE
Add cloud fraction and cloud height diagnostics

### PR DESCRIPTION
**Pull request by jamiebresch**
TYPE: enhancement

KEYWORDS: diag, cloud fraction, cloud height

DESCRIPTION OF CHANGES:
Add low/mid/high/total cloud fraction and cloud top/base height diagnostics.
Activated by adding in stream_list.atmosphere.diagnostics the following variables:
cldfrac_low_UPP
cldfrac_mid_UPP
cldfrac_high_UPP
cldfrac_tot_UPP
cldfrac_low_UM
cldfrac_mid_UM
cldfrac_high_UM
cldfrac_tot_UM_max
cldfrac_tot_UM_rand
cldht_top_UM
cldht_base_UM

LIST OF MODIFIED FILES:
M       src/core_atmosphere/diagnostics/Registry_convective.xml
M       src/core_atmosphere/diagnostics/convective_diagnostics.F

### CODE REVIEW

**Comment by jjguerrette** [comment]
@jamiebresch, do you mind targeting the JCSDA-internal fork instead?  Then you can easily assign reviewers as well.  Let me know if you have access difficulties.

https://github.com/JCSDA-internal/MPAS-Model

**Comment by jamiebresch** [comment]
remote: Permission to JCSDA-internal/MPAS-Model.git denied to jamiebresch.
fatal: unable to access 'https://github.com/JCSDA-internal/MPAS-Model/': The requested URL returned error: 403

**Comment by jamiebresch** [comment]
Close this PR and try re-forking my repo from JCSDA-internal.

**Comment by jjguerrette** [comment]
OK, if that does not work I will start a discussion with somebody at JCSDA.  We should be able to clear this up quickly.

**Pull request closed without merging**
