### PR TITLE
Add stream-function, velocity potential, and halo adjoint

### PR DESCRIPTION
**Pull request by byoung-joo**
KEYWORDS: halo exchange, adjoint 

DESCRIPTION OF CHANGES:
* This is a companion of JCSDA/mpas-jedi#361 .
* `stream_function` and `velocity_potential` are added to Registry as a `jedi-da` package.
* Adjoint of halo exchange is added (`mpas_dmpar_exch_halo_adj_field`). Only `mpas_dmpar_exch_halo_adj_field2d_real` was written because this is what is really used in JCSDA/mpas-jedi#361 .  

LIST OF MODIFIED FILES:
M       src/core_atmosphere/Registry.xml
M       src/framework/mpas_dmpar.F

### CODE REVIEW

**Comment by jjguerrette** [comment]
I suppose it might be nice to have the 1d exchange in case an adjoint model is ever added to MPAS-Model, but it would be untested and who knows how long in the future that would be needed!?!  So 2d is probably fine for now.  I'm not exactly sure how to review this, because I'm not familiar with any of the subroutines and derived types used.  Would it be worthwhile to have an MPAS-Model person look at it?

**Comment by byoung-joo** [comment]
Yes, MPAS-Model person's comment would be helpful because I might miss something.


The structure of `routine mpas_dmpar_exch_halo_field2d_real` is ... (in my view) ...

1. copy fieldCursor%array (where fieldCursor => field) to commListPtr % rbuffer (where commListPtr => sendList)
https://github.com/jjguerrette/MPAS-Model/blob/8927e0abc00341b725f7d5ae66741e1edd256606/src/framework/mpas_dmpar.F#L5486
2. local copy
https://github.com/jjguerrette/MPAS-Model/blob/8927e0abc00341b725f7d5ae66741e1edd256606/src/framework/mpas_dmpar.F#L5516
3. copy commListPtr % rbuffer (where commListPtr => recvList) to fieldCursor % array (where commListPtr => recvList)
https://github.com/jjguerrette/MPAS-Model/blob/8927e0abc00341b725f7d5ae66741e1edd256606/src/framework/mpas_dmpar.F#L5546

They all operate as A=B .

In adjoint routine, the operation became ` B’ = B' + A’ ; A’ = 0.0 `.

1. adding fieldCursor % array (where fieldCursor => field) to commListPtr % rbuffer (where commListPtr => recvList)
https://github.com/jjguerrette/MPAS-Model/blob/8927e0abc00341b725f7d5ae66741e1edd256606/src/framework/mpas_dmpar.F#L6247-L6248
2. local ...
https://github.com/jjguerrette/MPAS-Model/blob/8927e0abc00341b725f7d5ae66741e1edd256606/src/framework/mpas_dmpar.F#L6279-L6280
3. adding commListPtr % rbuffer (commListPtr => sendList) to fieldCursor % array (where fieldCursor => field)
https://github.com/jjguerrette/MPAS-Model/blob/8927e0abc00341b725f7d5ae66741e1edd256606/src/framework/mpas_dmpar.F#L6310-L6311

**Comment by liujake** [comment]
We do have some adjoint code of MPAS dynamic core to be incorporated into the MPAS model at some point, but I agree with JJ that we only need to include code for what we need at this point. I am not qualified to review these changes (may be no one), but will suggest the same strategy (not break the existing capabilities and cycling results) for moving forward.  @byoung-joo: Still better explicitly have a list of 3 modified/added files in the PR message.

**Comment by liujake** [comment]
Yes. Some quick look by a MPAS modeler will be helpful for 2 modified files, but may also be hard to review adjoint code. But this is not a PR to the model develop branch, not sure they will get time to review. So I am Ok to proceed without their review pending ctests and cycling results.

**Comment by liujake** [comment]
@svahl991 Not sure you were aware of this associated model PR for @byoung-joo MPAS-JEDI PR. I guess this needs to be included in the compilation and cycling tests.

**Review by liujake — APPROVED** [review]

**Comment by jjguerrette** [comment]
Are we ready to merge this now?

**Comment by byoung-joo** [comment]
> Are we ready to merge this now?
I think so... I will merge JCSDA/mpas-jedi#361 now.

**Comment by jjguerrette** [comment]
@byoung-joo, please keep the MPAS-Model branch around so that we can do a PR to the upstream repo later.

**Comment by jjguerrette** [comment]
> @byoung-joo, please keep the MPAS-Model branch around so that we can do a PR to the upstream repo later.

Actually it looks like you pushed the branch to my fork.  So I will keep it around.

**Comment by byoung-joo** [comment]
Yes, you're correct! I pushed the branch to your fork... though that might not be a recommended way.

**Pull request merged**
